#!groovy​

pipeline {
    agent none
    environment {
        JOB_WORKSPACE = 'workspace/ARGO'
        JOB_NAME = 'Argo'
    }
    stages {
        stage('container') {
            agent {
                dockerfile {
                    additionalBuildArgs '--build-arg BUILDER_UID=$(id -u)'
                }
            }
            environment {
                TALEND_PROJECT_DIR = "${WORKSPACE}/${env.JOB_WORKSPACE}"
                TALEND_BUILD = "${WORKSPACE}/target"
                TALEND_JOB_NAME = "${env.JOB_NAME}_harvester"
            }
            stages {
                stage('validation') {
                    steps {
                        //Moving in to the directory to execute the commands
                        dir(env.JOB_WORKSPACE) {
                            script {
                                if (env.GIT_PREVIOUS_SUCCESSFUL_COMMIT == null) {
                                    echo "No previous successful runs found, building"
                                } else {
                                    def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep servicelayer | wc -l").trim()
                                    if (strCount == "0") {
                                        echo "Skipping build since no files updated"
                                        currentBuild.result = "NOT_BUILT"
                                        CONTINUE_BUILD = false
                                    } else {
                                        echo "Changes found in the servicelayer module"
                                    }
                                }
                            }
                        }
                    }
                }
                stage('build') {
                    steps {
                        sh 'xvfb-run -a $TALEND_EXEC \
                            --clean_component_cache --disableShellInput -nosplash \
                            -consoleLog --launcher.suppressErrors \
                            -data $TALEND_WORKSPACE \
                            -componentDir $TALEND_CUSTOM_COMPONENTS \
                            -application au.org.emii.talend.codegen.Generator \
                            -jobName ${TALEND_JOB_NAME} \
                            -projectDir ${TALEND_PROJECT_DIR} \
                            -targetDir ${TALEND_BUILD}'
                    }
                }
            }
            post {
                success {
                    dir('target/') {
                        archiveArtifacts artifacts: '*.zip', fingerprint: true, onlyIfSuccessful: true
                    }
                }
            }
        }
    }
}
