#!groovy​

pipeline {
    agent none
    parameters {
        string(name: 'workspace', defaultValue: 'workspace/AUV_VIEWER_TRACKS')
        string(name: 'talend_job_name', defaultValue: 'AUV_VIEWER_TRACKS_harvester')
    }
    stages {
        stage('validation') {
            agent { label 'master' }
            steps {
                //Moving in to the directory to execute the commands
                dir(${params.workspace}) {
                    script {
                        if (env.GIT_PREVIOUS_SUCCESSFUL_COMMIT == null) {
                            echo "No previous successful runs found, building"
                        } else {
                            def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep servicelayer | wc -l").trim()
                            if (strCount == "0") {
                                echo "Skipping build since no files updated"
                                currentBuild.result = "NOT_BUILT"
                                CONTINUE_BUILD = false
                            } else {
                                echo "Changes found in the servicelayer module"
                            }
                        }
                    }
                }
            }
        }
        stage('container') {
            agent {
                dockerfile {
                    additionalBuildArgs '--build-arg BUILDER_UID=${JENKINS_UID:-498}'
                }
            }
            environment {
                TALEND_PROJECT_DIR = "${WORKSPACE}/${params.workspace}"
                TALEND_BUILD = "${WORKSPACE}/target"
                TALEND_JOB_NAME = ${params.talend_job_name}
            }
            stages {
                stage('build') {
                    steps {
                        sh 'xvfb-run -a $TALEND_EXEC \
                            --clean_component_cache --disableShellInput -nosplash \
                            -consoleLog --launcher.suppressErrors \
                            -data $TALEND_WORKSPACE \
                            -componentDir $TALEND_CUSTOM_COMPONENTS \
                            -application au.org.emii.talend.codegen.Generator \
                            -jobName ${TALEND_JOB_NAME} \
                            -projectDir ${TALEND_PROJECT_DIR} \
                            -targetDir ${TALEND_BUILD}'
                    }
                }
            }
            post {
                success {
                    dir('target/') {
                        archiveArtifacts artifacts: '*.zip', fingerprint: true, onlyIfSuccessful: true
                    }
                }
            }
        }
    }
}
